<?php

/**
*
* @   Script Name :   cleandb.phtml
* @   Author      :   NIKO28
* @   Skype       :   nicolo3767
* @   Project     :   DBOOR Full Decoded
*
**/
?>

<table align="center">
<tr><td>
<font color="red">Attenzione! In questo modo cancellerai tutti i messaggi e i report letti!</font> <br /><br />
</td></tr><tr><td>
<form action="cleandb.php" method="POST">
	<input type="submit" value="Pulisci!" id="Submit" name="Submit" />
</form>
</td></tr>
</table>