<table align="center">
<tr><td>
Villaggio Selezionato: <?php echo $this->data['village_name']; ?>
</td>
</tr>
<tr><td>In totale possiedi <?php echo $this->data['gold_num']; ?> <img src="assets/x.gif" class="gold" alt="Gold" title="Gold"></td></tr>
</tr>
<tr><td>In totale possiedi <?php echo $this->data['evasione']; ?> <img src="assets/x.gif" class="unit u99" alt="Evasioni" title="Evasioni"></td></tr>
<tr><td>
<form action="evasione.php" method="POST">
	<input type="submit" value="Aggiungi!" id="Submit" name="Submit" />
</form>
</td></tr><tr><td>
<?php
if(isset($this->error))
echo $this->error;
?></td></tr>
</table>