<?php

/**
*
* @   Script Name :   index.phtml
* @   Author      :   NIKO28
* @   Skype       :   nicolo3767
* @   Project     :   DBOOR Full Decoded
*
**/

require_once( LANG_UI_PATH . 'index.php' );
echo '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3c.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="eg" lang="eg">
	<head>
		<title>';
echo $this->appConfig['page'][$this->appConfig['system']['lang'] . '_title'];
echo '</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta http-equiv="content-script-type" content="text/javascript" />
		<meta http-equiv="content-style-type" content="text/css" />
		<meta content="';
echo $this->appConfig['page']['meta-tag'];
echo '" name="description">
		<meta content="';
echo $this->appConfig['page']['meta-tag'];
echo '" name="keywords">
        <link rel="stylesheet" type="text/css" href="assets/indx/css/style.css';
echo $this->getAssetVersion(  );
echo '"/>
		<meta name="google-site-verification" content="vTjsRxnpRzHRJvw5E3uOiAA-jcGayHNOw_SEAD93-fc" />
		<link rel="shortcut icon" href="assets/favicon.ico" type="image/x-icon" />
		';
echo '<s';
echo 'cript type="text/javascript">var d3l=';
echo ($this->appConfig['system']['lang'] == 'ar' ? '180' : '-600');
echo ';</script>
		';
echo '<s';
echo 'cript src="assets/core.js';
echo $this->getAssetVersion(  );
echo '" type="text/javascript"></script>';
?>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/it_IT/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<?php
echo'
	</head>
<body>

        <div id="trv_wrapper">
            <div id="trv_page">
                
           <div id="partnerMod"></div>
                <!--Header-->
                <div id="trv_header">
                    <div class="trv_header_info">

                    </div>
                </div>
                <div id="headline"></div>
                <div class="trv_form_part">
                    <h2><br /></h2>
                    <ul>
                        <li>250x</li>
                        <li>250x</li>
                        <li>20x</li>
                    </ul>
					<form name="login" action="index.php" method="post">
        			<div style="position: absolute;  top: 150px; left: 8px">    
					<input type="text" name="name" placeholder="Username" type="text" value=""/>&nbsp;&nbsp;<br />
        </div>
        <div style="position: absolute;  top: 180px; left: 8px">    
			<input name="password" type="password" placeholder="Password" value="" />		
        </div>
        
        <div style="position: absolute;  top: 132px; left: 49px">
        <input type="image" src="/assets/indx/img/login.png" onmouseover="this.src=\'/assets/indx/img/login.png\'" onmouseout="this.src=\'/assets/indx/img/login.png\'" onclick="form.submit()" />
        </div>
        
        <div class="text" style="position: absolute;  top: 45px; left: 285px"><p class="stats">';
		echo $this->data['players_count'];
		echo '</p></div>
        <div class="text" style="position: absolute;  top: 80px; left: 270px"><p class="stats">';
		echo $this->data['online_players_count']; 
		echo '</p></div>
        
        <br />
        
        </form>
        <!-- NEWS 1 -->
        <div style="position: absolute;  top: 150px; left: 199px;height: 70px;">
        <font size="1" color="gray"></font>        <br />
        <font size="1"></font><!--News Mehet ide--><font size="2"><a href=\'register.php\'><b>REGISTER NOW</b></a></font>        </div>
        
  
        
        <div style="position: absolute;  top: 523px; left: -550px">
        </div>
        
        <div style="position: absolute;  top: 206px; left: 8px">
        <font size="1"></font>
        </div>
                </div>
                <div class="trv_slider_area">
                    <!-- Facebook-Feld-->
                    <div class="trv_fb_field">
                    <div class="fb-like-box" data-href="'.$this->appConfig['system']['facebook_url'].'" data-width="220" data-height="100" data-show-faces="true" data-stream="false" data-show-border="true" data-header="true"></div>
                    </div>
                    <!-- Screenshot-Slider -->
                    <div id="trv_wrap_img">
                        <h3>'.nl2br( $this->data['news_text'] ).'</h3>
                        <div class="trv_image_carousel">
                        
                            <div class="clearfix"></div>
                    
                        </div>
                    </div>
                </div>
                <!-- Footer -->
                <div id="trv_footer">
                    <div class="trv_footer_2"></div>
                </div>
            </div>
        </div>
        <div id="trv_overlay">  </div>
        <!-- Layer 1 -->
        <div id="trv_layer1" class="trv_layer">
            <a class="trv_close" onclick="closeLayer();" href="#" ></a>
        </div>
        <!-- Layer 2 -->
        <div id="trv_layer2" class="trv_layer">
            <a class="trv_close" onclick="closeLayer();" href="#"></a>
        </div>
        <!-- Layer 3 -->
        <div id="trv_layer3" class="trv_layer">
            <a class="trv_close" onclick="closeLayer();" href="#"></a>
        </div>
        <!-- Layer 4 -->
        <div id="trv_layer4" class="trv_layer">
            <a class="trv_close" onclick="closeLayer();" href="#"></a>
        </div>
        <!-- Layer 5 -->
        <div id="trv_layer5" class="trv_layer">
            <a class="trv_close" onclick="closeLayer();" href="#"></a>
        </div>

</body>
<script type="text/javascript">init();</script>
</html>';
?>
