<?php

/**
*
* @   Script Name :   medals.phtml
* @   Author      :   NIKO28
* @   Skype       :   nicolo3767
* @   Project     :   DBOOR Full Decoded
*
**/
?>

<table align="center">
<tr><td>
<font color="red">Attenzion! Premendo più volte "Vai!" assegnerai le medaglie per più settimane</font> <br /><br />
</td></tr><tr><td>
<form action="medals.php" method="POST">
	<input type="submit" value="Vai!" id="Submit" name="Submit" />
</form>
</td></tr>
</table>