<?php

/**
*
* @   Script Name :   multi.phtml
* @   Author      :   NIKO28
* @   Skype       :   nicolo3767
* @   Project     :   DBOOR Full Decoded
*
**/
?>

<table align="center">
<tr><td>
<font color="red">Attenzione! In questo modo i giocatori con lo stesso ip saranno bannati!</font> <br /><br />
</td></tr><tr><td>
<form action="multi.php" method="POST">
	<input type="submit" value="Banna!" id="Submit" name="Submit" />
</form>
</td></tr>
</table>