<?php

/**
*
* @   Script Name :   shownvill.phtml
* @   Author      :   NIKO28
* @   Skype       :   nicolo3767
* @   Project     :   DBOOR Full Decoded
*
**/

echo '<p class="f16" align="center">';
echo text_newvill_lang;
echo '</p>
';
echo $this->getFlashContent( 'assets/anm/war/nvil.swf', 500, 350 );
echo '<p class="f16" align="center"><a href="village1.php">';
echo text_gotonext_lang;
echo '</a></p>';
?>
