 
<br />
<div class="gid27"> 
<body> 
    <table id="own" cellpadding="1" cellspacing="1"> 
        <thead> 
            <tr> 
                <th colspan="3">Own artefacts</th> 
            </tr> 
            <tr> 
                <td>Nome</td> 
                <td>Effetto</td> 
                <td>Villaggio</td> 
            </tr> 
        </thead> 

        <tbody>
        <?php
        $query = mysql_query("SELECT * FROM p_artefacts WHERE owner=".$this->player->playerId."");
        if(mysql_num_rows($query) > 0)
        {        
            while($result = mysql_fetch_assoc($query))
            {
				$effetto = '';
				switch($result['type']){
					case 1:
						$effetto = 'Villaggio';
						break;
					case 2:
						$effetto = 'Account';
						break;
					case 3:
						$effetto = 'Unico';
						break;
							
				}
				$villaggio = mysql_query("SELECT `village_name` FROM  `p_villages` WHERE  `player_id` =".$result['owner']."");
				$villaggio = mysql_fetch_row($villaggio);
			$villaggio = $villaggio['0'];
                echo '<tr>';
                echo '<td>'.$result['name'].'</td>';
				echo '<td>'.$effetto.'</td>';
                echo '<td>'.$villaggio.'</td>';
                echo '</tr>';
            }
        }
        else
        {
            echo ' <tr><td colspan="4" class="none">you dont have any artefact1</td></tr>';
        }
        ?> 
           
        </tbody> 
    </table> 

    <table id="near" cellpadding="1" cellspacing="1"> 
        <thead> 
            <tr> 
                <th colspan="3">Artefacts in this server</th> 
            </tr> 

            <tr> 
                <td>Nome</td> 
                <td>Effetto</td> 
                <td>Villaggio</td> 
            </tr> 
        </thead> 

        <tbody> 
        <?php
        $query = mysql_query("SELECT * FROM p_artefacts");
        if(mysql_num_rows($query) > 0)
        {        
            while($result = mysql_fetch_assoc($query))
            {
				$effetto = '';
				switch($result['type']){
					case 1:
						$effetto = 'Villaggio';
						break;
					case 2:
						$effetto = 'Account';
						break;
					case 3:
						$effetto = 'Unico';
						break;
							
				}
				$villaggio = mysql_query("SELECT `village_name` FROM  `p_villages` WHERE  `player_id` =".$result['owner']."");
				$villaggio = mysql_fetch_row($villaggio);
			$villaggio = $villaggio['0'];
                echo '<tr>';
                echo '<td>'.$result['name'].'</td>';
				echo '<td>'.$effetto.'</td>';
                echo '<td>'.$villaggio.'</td>';
                echo '</tr>';
            }
        }
        else
        {
            echo ' <tr><td colspan="4" class="none">you dont have any artefact1</td></tr>';
        }
        ?> 
        </tbody> 
    </table> 
</div> 

