<?php

/**
*
* @   Script Name :   footer.phtml
* @   Author      :   NIKO28
* @   Skype       :   nicolo3767
* @   Project     :   DBOOR Full Decoded
*
**/

	require_once( LANG_UI_PATH . 'footer.php' );
	echo '<ul class="menu menu2">
	<li><a href="index.php">';
	echo LANGUI_FOOTER_MAIN;
	echo '</a></li>
	<li><a href="manual.php">';
	echo LANGUI_FOOTER_MANUAL;
	echo '</a></li>
	<li><a href="training.php">';
	echo LANGUI_FOOTER_TRAINING;
	echo '</a></li><script type="text/javascript" src="http://download.skype.com/share/skypebuttons/js/skypeCheck.js"></script>
	<li><a href="skype:nicolo3767?add"><font color=”blue”> Full Game By </font> <font color=#DD0000>NIKO28 </font></a></li>
</ul>';
?>